#! /usr/bin/perl -sW

# We are going to read the build file (a log of the source package building)
# in slurp mode, then we will check each possible error (not exhaustively)
# detected by lintian (a tool that checks if the package is conform with
# Debian policy) and correct the package building configuration files 
# accordingly.

use strict;

if(our$h) {
    print "correct_lintian source_build_log\n\nDescritpion:\n\tCorrects the debian folder built by dh_make using the .build file\n\tgenerated by 'debuild -S' command.\n\nOptions:\n";
    exit 0;
}

print "Starting configuration files edition due to lintian messages.\n";

my$buildfilename = shift;
open BUILDLOG, $buildfilename;
$/ = undef;
my$log = <BUILDLOG>;    # the entire debuild log

$log =~ m/Now running lintian\.\.\.\n(.*)\nFinished running lintian/s;
my$lintianLog = $1;  # the lintian part of the log

# Opening debian/control
open CONTROL, "debian/control" or die($!);
my$control = <CONTROL>;
close CONTROL;
# Opening debian/copyright
open COPYRIGHT, "debian/copyright" or die($!);
my$copyright = <COPYRIGHT>;
close COPYRIGHT;

# Opening log file
my$do_log = open LOG, ">", "$ENV{LOGFILE}";
if($do_log) {
    my$date = scalar localtime(time);
    print LOG "correct_lintian.pl log file. This log lists edits made by the script and warnings/errors that happened during debian package building. You may want to correct them and launch a new build.\n\nTimestamp: $date\n\n";
}

# Adding descriptions
my$binpackdesc = $ENV{BINPACKAGEDESCFILE};
my$libpackdesc = $ENV{LIBPACKAGEDESCFILE};
if ( open DESC, $binpackdesc ) {
    my$desc = <DESC>;
    $desc =~ s/\n/\n /gs;
    my$name = $ENV{BINPACKAGENAME};
    $control =~ s/(Package: $name[\s]+Architecture: .*?[\s]+Depends:.*?[\s]+Description:) <.*?>[\s]+ <.*?>/$1 $desc\n/s;
    close DESC;
}
if ( open DESC, $libpackdesc ) {
    my$desc = <DESC>;
    my$name = $ENV{LIBPACKAGENAME};
    my@descriptions = split /\n\n/, $desc;
    $descriptions[0] =~ s/\n/\n /gs;
    $descriptions[1] =~ s/\n/\n /gs;
    $control =~ s/(Package: $name[\s]+Section: libs[\s]+Architecture:.*?[\s]+Depends:.*?[\s]+Description:) <.*?>[\s]+ <.*?>/$1 $descriptions[0]\n/s;
    $control =~ s/(Package: $name-dev[\s]+Section:.*?[\s]+Architecture:.*?[\s]+Depends:.*?[\s]+Description:) <.*?>[\s]+ <.*?>/$1 $descriptions[1]\n/s;
    close DESC;
}
# removing empty lines
$control =~ s/\n{2,}/\n\n/sg;

# Editing copyright
my$url = $ENV{HOMEPAGE};
#my@devnames = split /;/, $ENV{DEVNAMES};
#my@devmails = split /;/, $ENV{DEVMAILS};
#my@devyears = split /;/, $ENV{DEVYEARS};
$copyright =~ s#(Source:) <url://example.com>#$1 $url#;
#$copyright =~ s/(Copyright:) <.+?> <.+?>\n\s+? <.+?> <.+?>\n/$1 

# Matching errors and correcting
if ( $lintianLog =~ /package-needs-versioned-debhelper-build-depends (.*?)[\s]/ ) {
    my$dh_version = $1;
    $control =~ s/debhelper (\(.*?\))/debhelper \(>= $dh_version\)/;
    print LOG "build depends debhelper version changed from $1 to (>= $dh_version)\n" if $do_log;
}
if ( $lintianLog =~ /out-of-date-standards-version \d\.\d\.\d \(current is (\d\.\d\.\d)\)/ ) {
    my$std_version = $1;
    $control =~ s/Standards-Version: (\d\.\d\.\d)/Standards-Version: $std_version/;
    print LOG "standards version changed from $1 to $std_version\n" if $do_log;
}
if ( $lintianLog =~ /ancient-standards-version \d\.\d\.\d \(current is (\d\.\d\.\d)\)/ ) {
    my$std_version = $1;
    $control =~ s/Standards-Version: (\d\.\d\.\d)/Standards-Version: $std_version/;
    print LOG "standards version changed from $1 to $std_version\n" if $do_log;
}
if ( $lintianLog =~ /debhelper-but-no-misc-depends/ ) {
    $control =~ s/(Package: (.*?-dev)[\s]+Section:.*?[\s]+Architecture:.*?[\s]+Depends:.*?)([\s]+Desc)/$1, \${misc:Depends}$3/s;
    print LOG "added missing dependencies for $2 package\n" if $do_log;
}
if ( $lintianLog =~ /bad-homepage/ ) {
    $control =~ s/(Homepage: )<.*?>/$1$ENV{HOMEPAGE}/g;
    print LOG "updated homepage to $ENV{HOMEPAGE}\n" if $do_log;
}
if ( $lintianLog =~ /binary-without-manpage/ ) {
    print LOG "WARNING: Each binary in /usr/bin, /usr/sbin, /bin, /sbin or /usr/games should have a manual page.\n
\tIf the man pages are provided by another package on which this package depends, we may not be able to determine\n
\tthat man pages are available. In this case, ignore this warning\n" if $do_log;
}


# Writing in debian/control
open CONTROL, ">", "debian/control" or die($!);
print CONTROL $control;
# Writing in debian/copyright
open COPYRIGHT, ">", "debian/copyright" or die($!);
print COPYRIGHT $copyright;

# Closing files
close CONTROL;
close COPYRIGHT;
close BUILDLOG;
close LOG if $do_log;


print "Configuration files edited ! You can find what has been changed in $ENV{LOGFILE}\n";
